#!/usr/bin/env python3

import collections
import logging
import os
import sys

import aa_scan3.utils
import aa_scan3.plugins

description = """
aa-scan3 parses the file passed in parameter, and generates an
AppArmor profile for it. The file must be a fully-qualified path,
but relative to the target root directory (see options, below).
"""

plugins_description = """
aa-scan3 is plugins-based. The file to scan is passed to each plugin
in turn, and if the plugin knows how to scan that file, it will do
so and emit (part of) a profile; if a plugin does not know how to
handle a file, it just ignores it.
"""

epilog = """
See also the following resources:
    apparmor(7), apparmor.d(5), apparmor_parser(8),
    and the AppArmor Wiki <http://wiki.apparmor.net>
"""


def main():
    def dir_exists(d):
        if not os.path.isdir(d):
            parser.error('no such directory: {!r}'.format(d))
        return os.path.abspath(d)

    parser = aa_scan3.utils.AAScanArgParser(description=description, epilog=epilog,
                                            usage='%(prog)s [options [...] FILE | --help]')

    parser.add_argument('--root-dir', '-r', metavar='DIR', required=True, type=dir_exists,
                        help='Treat DIR as the target root directory')
    parser.add_argument('--staging-dir', '-s', metavar='DIR', required=True, type=dir_exists,
                        help='Treat DIR as the staging (aka sysroot) directory')
    parser.add_argument('--output-file', '-o', metavar='FILE',
                        help='Emit the profile in FILE; default is to emit on stdout')
    parser.add_argument('--enforce', '--complain', default='--enforce',
                        action=aa_scan3.utils.AAScanArgParser.ToggleAction(['--enforce']),
                        help='Set profiles in enforced or complain mode, respectively.')
    parser.add_argument('--debug', action='store_true',
                        help='Generate a lot of debugging information.')
    parser.add_argument('file', metavar='FILE',
                        help='The file to scan and generate an AppArmor profile for')

    # Hack: option group with no arg, just to have a nice
    # introduction to plugins
    parser.add_argument_group('PLUGINS', description=plugins_description)

    plugins = collections.defaultdict(dict)
    plugins_type = collections.defaultdict(set)
    for plugin in aa_scan3.plugins.plugins:
        p = aa_scan3.plugins.plugins[plugin]
        plugins[plugin]['type'] = set()
        if "once" in dir(p.Scanner):
            plugins[plugin]['type'].add("scan")
            plugins_type['once'].add(plugin)
        if "scan" in dir(p.Scanner):
            plugins[plugin]['type'].add("scan")
            plugins_type['scan'].add(plugin)
        if "mangle" in dir(p.Scanner):
            plugins[plugin]['type'].add("mangle")
            plugins_type['mangle'].add(plugin)
        if "emit" in dir(p.Scanner):
            plugins[plugin]['type'].add("mangle")
            plugins_type['emit'].add(plugin)
        if len(plugins[plugin]['type']) == 0:
            raise NotImplementedError('Plugin {} is neither scan nor mangle'.format(plugin))

    for plugin in sorted(plugins):
        p = aa_scan3.plugins.plugins[plugin]
        group = parser.add_argument_group(title='Plugin {} [{}]'.format(plugin,
                                                                        ', '.join(plugins[plugin]['type'])),
                                          description=p.__doc__)
        plugins[plugin]["scanner"] = p.Scanner(aa_scan3.utils.AAScanArgParser._ArgGroupPlugin(plugin,
                                                                                              group))

    args = parser.parse_args()

    profile = aa_scan3.utils.AAprofile(args.file)

    logging.basicConfig(stream=sys.stdout, format='%(message)s',
                        level=logging.DEBUG if args.debug else logging.WARNING)

    base_args = ['root_dir', 'staging_dir']
    for plugin in plugins:
        setattr(plugins[plugin]["scanner"], 'profile', profile)
        setattr(plugins[plugin]["scanner"], 'logger', aa_scan3.utils.AALogger(plugin))
        for arg in base_args:
            setattr(plugins[plugin]["scanner"], arg, getattr(args, arg))
        for arg in [a for a in dir(args) if a.startswith(plugin+'_')]:
            setattr(plugins[plugin]["scanner"], arg[len(plugin)+1:], getattr(args, arg))


if __name__ == "__main__":
    main()
